//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyBroker.DBSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyResource
    {
        public int ResourceId { get; set; }
        public int CompanyId { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool Active { get; set; }
    }
}
